// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class GhostSaveBindings
    {
        readonly ICloudCodeService k_Service;
        public GhostSaveBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<Dictionary<string,string>> GetGhostData()
        {
            return await k_Service.CallModuleEndpointAsync<Dictionary<string,string>>(
                "CloudSave",
                "GetGhostData",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task SaveGhostData(string ghostData, string ghostName)
        {
            await k_Service.CallModuleEndpointAsync(
                "CloudSave",
                "SaveGhostData",
                new Dictionary<string, object>()
                {
                    {"ghostData", ghostData},
                    {"ghostName", ghostName},
                });
        }

        public async Task InitGhostData()
        {
            await k_Service.CallModuleEndpointAsync(
                "CloudSave",
                "InitGhostData",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
