// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class LeaderboardAdmin
    {
        readonly ICloudCodeService k_Service;
        public LeaderboardAdmin(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task CreateLeaderboard(string leaderboardName)
        {
            await k_Service.CallModuleEndpointAsync(
                "CloudSave",
                "CreateLeaderboard",
                new Dictionary<string, object>()
                {
                    {"leaderboardName", leaderboardName},
                });
        }
    }
}
